### ISSUE TITLE
Snaps found by name provide channels/tracks but not Snaps found by section

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/snapd.dart#46]
When using

```dart
final snaps = await client.find(name: name);
```

you end up with a list of snaps which's channels and tracks lists are not empty. But when finding them by a section name, you get your snaps fine but with empty channels and tracks lists.

```dart
final snaps = await client.find(section: section);
```

Is this intended? If yes and I am not understand this correctly, sorry.

**Comment by robert-ancell** [comment]
Yes, this is done on the server side due to the cost of getting the channel map from the database. In gnome-software, when you do a search we do a second find when you select a particular snap to get the full information to show. It's annoying and requires some careful work if you are caching results.

AFAIK this is the only piece of information that is ommitted when not searching a specific snap.

**Comment by Feichtmeier** [comment]
Okay! Thanks for the clarification 🤠
This is how I currently do it. I make a search by name once a snap tile is selected from the grids.
