### ISSUE TITLE
Refresh skips over the classic flag if the channel confinments differ

### ISSUE THREAD

**Issue by Feichtmeier** [canonical/snapd.dart#65]
Installing a classic snap by name and classic=true flag works
When you then refresh the same app via SnapDClient.refresh you get this error:

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: SnapdException(kind: snap-needs-classic, message: snap "notepadqq" requires classic confinement)
#0      _SnapdErrorResponse.change
package:snapd/src/snapd_client.dart:908
#1      SnapdClient._postAsync
package:snapd/src/snapd_client.dart:1221
<asynchronous suspension>
#2      SnapdClient.refresh
package:snapd/src/snapd_client.dart:1127
<asynchronous suspension>
#3      SnapModel.refreshSnapApp
package:software/…/common/snap_model.dart:268
<asynchronous suspension>
``` 

This did not happen with eclipse though. Maybe because notpadqq has a classic confinment in the one channel and strict in the other?

![grafik](https://user-images.githubusercontent.com/15329494/173338456-babf0f09-e479-41f2-989b-855a224070be.png)

**Comment by robert-ancell** [comment]
This is a server side error. Every time you do an operation on a classically confined snap you need to pass the flag to confirm you are OK with this. On the command line the command just fails and suggests you re-run with --classic. So a GUI needs to check each time if the snap is classic and pass that flag. Since we have shown the information visually we don't need to prompt the user like on the command line.

As you saw, each version of a snap might have different confinement, so it could change during a refresh. The behaviour should probably be:
- If the snap is not installed and the requested version is classically confined, then pass the flag.
- If the snap is being refreshed and the already installed version is classically confined, then pass the flag.
- If you think the new version to be installed is classically confined and have shown that to the user, then pass the flag.
- In all other cases, don't pass the flag, but catch the error and prompt or inform the user in case the refreshed version turns out to be classically confined - there is a race here in that the server might update the version just before you click refresh.

**Comment by robert-ancell** [comment]
We probably should make different exception classes at some point, but for now just checking that SnapdException.kind == 'snap-needs-classic' should be sufficient.

**Comment by Feichtmeier** [comment]
Hm, but the refresh command doesn't have the flag, that's what I meant with I can't pass it
https://github.com/canonical/snapd.dart/blob/main/lib/src/snapd_client.dart#L1120
